#!/bin/bash
nsamples=10
sleeptime=3
pid=$1 
allthread=0
if [ $pid = '-a' ]; then
  pid=$2
  allthread=1
fi

if [ x$2 = 'x-a' ]; then
  allthread=1
fi

flamegraph=`dirname $0`/flamegraph.pl

for x in $(seq 1 $nsamples)
  do
    echo sampling $x... >/dev/stderr
    jstack $pid
    sleep $sleeptime
  done |
awk '
  BEGIN { s = ""; runnable=0; } 
  /^$/ { if (s != "") print s, 1; s = ""; runnable=0; }
  /java.lang.Thread.State: RUNNABLE/ { runnable=1; } 
  /^	at / { if ('$allthread' || runnable) { if (s != "") { s = $2 ";" s } else { s = $2 } } }
  END { if (s != "") print s, 1 }' |
$flamegraph >$pid.svg
