#!/bin/bash
nsamples=10
sleeptime=3
pid=$1 
allthread=0
if [ $pid = '-a' ]; then
  pid=$2
  allthread=1
fi

if [ x$2 = 'x-a' ]; then
  allthread=1
fi

i=0
for x in $(seq 1 $nsamples)
  do
    i=`expr $i + 1`
    echo sampling $i... >/dev/stderr
    jstack $pid
    sleep $sleeptime
  done | 
awk '
  BEGIN { s = ""; runnable=0; } 
  /^$/ { if (s != "") print s; s = ""; runnable=0; }
  /java.lang.Thread.State: RUNNABLE/ { runnable=1; } 
  /^	at / { if ('$allthread' || runnable) { if (s != "") { s = s ";" $2 } else { s = $2 } } }
  END { if (s != "") print s }' |
sort | uniq -c | sort -r -n -k 1,1
