#!/bin/bash
nsamples=10
sleeptime=3
if [ x$1 = 'x-p' ]; then
    pid=$2
else
    pid=`pidof $1 | awk '{print $1}'` 
fi

if [ x$pid = x ]; then
    echo no program is specified.
    exit 1
fi

for x in $(seq 1 $nsamples)
  do
    echo sampling $x... >/dev/stderr
    gdb -ex "set pagination 0" -ex "thread apply all bt" -batch -p $pid 2>/dev/null
    sleep $sleeptime
  done | 
awk '
  BEGIN { s = ""; } 
  /^Thread/ { print s; s = ""; } 
  /^\#/ { $4 = $3 != "in" ? $2 : $4; if (s != "" ) { s = s ";" $4} else { s = $4 } } 
  END { print s }' | 
sort | uniq -c | sort -r -n -k 1,1
