#!/bin/bash
nsamples=10
sleeptime=3
pid=`pidof $1` 

i=0
for x in $(seq 1 $nsamples)
  do
    i=`expr $i + 1`
    echo sampling $i... >/dev/stderr
    gdb -ex "set pagination 0" -ex "thread apply all bt" -batch -p $pid 2>/dev/null
    sleep $sleeptime
  done | 
awk '
  BEGIN { s = ""; } 
  /^Thread/ { print s; s = ""; } 
  /^\#/ { $4 = $3 != "in" ? $2 : $4; if (s != "" ) { s = s ";" $4} else { s = $4 } } 
  END { print s }' | 
sort | uniq -c | sort -r -n -k 1,1
