#!/bin/bash
nsamples=10
sleeptime=3

if [ x$1 = 'x-p' ]; then
    pid=$2
    prefix=''
else
    prefix="$1-"
    pid=`pidof $1 | awk '{print $1}'` 
fi

if [ x$pid = x ]; then
    echo no program is specified.
    exit 1
fi

flamegraph=`dirname $0`/flamegraph.pl

for x in $(seq 1 $nsamples)
  do
    echo sampling $x... >/dev/stderr
    gdb -ex "set pagination 0" -ex "thread apply all bt" -batch -p $pid 2>/dev/null
    sleep $sleeptime
  done | 
awk '
  BEGIN { s = ""; } 
  /^Thread/ { print s, 1; s = ""; } 
  /^\#/ { $4 = $3 != "in" ? $2 : $4; if (s != "" ) { s = $4 ";" s} else { s = $4 } } 
  END { print s, 1 }' | $flamegraph >${prefix}$pid.svg
